---
- name: restart supervisor
  service: name=supervisor state=restarted
  become: yes

- name: start supervisor
  service: name=supervisor state=started
  become: yes

- name: enable supervisor
  service: name=supervisor enabled=yes
  become: yes
